name: Terraform Apply / Destroy

on:
  push:
    branches:
      - main  

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.0

      - name: Terraform Init
        run: terraform -chdir=terraform init

      - name: Terraform Plan & Apply
        run: |
          echo "Running Terraform plan..."
          terraform -chdir=terraform plan -out=tfplan
          echo "Applying Terraform..."
          terraform -chdir=terraform apply -auto-approve tfplan
